name: build docker image and rollout ECS

on:
  push:
    branches:
      - main
      - dev

env:
  ECR_REGISTRY: 213446053867.dkr.ecr.us-west-2.amazonaws.com
  ECR_REPOSITORY: dachi-test-image

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    container: dachichang/devops-all-in-one:v0.2.1

    steps:
      - name: build docker image
        run: |
          set -x
          env
          echo $ECR_REPOSITORY
