name: build docker image and rollout ECS

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    container: dachichang/devops-all-in-one:v0.2.2
    outputs:
      ecr_image: ${{ steps.build-image.ecr_image }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login ECR
        run: |
          set -x
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build image and Push
        id: build-image
        run: |
          set -x
          env
          APP_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8)
          DOCKER_IMAGE_TAG_NAME="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
          DOCKER_IMAGE_TAG_SHA="${ECR_REGISTRY}/${ECR_REPOSITORY}:${APP_SHA_SHORT}"
          docker build --platform linux/amd64 \
            -t $DOCKER_IMAGE_TAG_NAME \
            -t $DOCKER_IMAGE_TAG_SHA \
            .
          docker push $DOCKER_IMAGE_TAG_NAME
          docker push $DOCKER_IMAGE_TAG_SHA
          echo "ecr_image=${DOCKER_IMAGE_TAG_SHA}" >> "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
        env:
          ECR_REPOSITORY: dachi-test-image
          IMAGE_TAG: ${{ github.ref_name }}

  rollout-ecs:
    name: Rollout ECS
    runs-on: ubuntu-latest
    container: dachichang/devops-all-in-one:v0.2.2
    needs: build-docker-image

    steps:
      - name: Rollout to ECS
        run: |
          set -x
          echo "rollout to ECS"
          echo $ECR_IMAGE
        env:
          ECR_IMAGE: ${{ needs.build-docker-image.outputs.ecr_image }}
