name: build docker image and rollout ECS

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ vars.ECR_REPOSITORY }}
  ECR_REPOSITORY: dachi-test-image

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    container:
      image: dachichang/devops-all-in-one:v0.2.2
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: login ECR
        run: |
          set -x
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: build image
        run: |
          set -x
          TAG_NAME="${ECR_REGISTRY}/{$ECR_REPOSITORY}:latest"
          echo $TAG_NAEM
